server:
  port: 8080

spring:
  application:
    name: ai-incident-investigator

  datasource:
    url: jdbc:postgresql://localhost:5432/incident_investigator
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  ai:
    ollama:
      base-url: http://localhost:11434

      chat:
        model: llama3.1

      embedding:
        model: nomic-embed-text

    vectorstore:
      pgvector:
        index-type: HNSW
        initialize-schema: true
        distance-type: COSINE_DISTANCE
        dimensions: 768

    mcp:
      client:
        streamable-http:
          connections:
            github:
              url: http://localhost:8889
logging:
  level:
    com.aii: DEBUG
    org.springframework.ai.mcp: DEBUG
    io.modelcontextprotocol: DEBUG
    org.springframework.web.client: DEBUG
    org.springframework.web.reactive.function.client: DEBUG